############################################################## Generic Parameters ###################################################################################

config: './run_configs/keras_config.yaml'

config_filename: keras_config.yaml

description: >
  Template for the config files to run

### Type of model

model_class : None

### Type of model

network : None

### model_name 

model_name : None

### train model 
train : True

### save model 

save : True

### save path : if None then the system will save the model in model_weights/model_class/network/weights/

save_path : None

### testing model

test : True

### Visualize 

Visualize : False

### Submit

submit : False

############################################################## Train Method input parameters  #########################################################################


### number of steps to train on
nb_steps : 10000

### 
action_repetition : 1

## callback class that will be called at every iteration and at every epoch end 
### available by default keras-rl are the followiing : ['TestLogger','TrainEpisodeLogger','TrainIntervalLogger','FileLogger','Visualizer','ModelIntervalCheckpoint']
callbacks : None

## How verbose should the system be 
verbose :1

nb_max_start_steps:0

start_step_policy:None

log_interval:10000


############################################################## Test Method input parameters  #########################################################################

### number of episodes to test on
test_nb_episodes:1

### max number of steps per epsiode
test_nb_max_episode_steps : 500
