############################################################## Generic Parameters ###################################################################################

config : './config/actor_critic.yaml' 

## parent configuration
parent_config : './config/keras_config.yaml'

config_filename : actor_critic.yaml

description : "> \n config for the example actor critic provided in the crowdAI challenge"

### Type of model

model_class : actor_critic

### Type of model

network : example

### model_name 

model_name : actor_critic_example

### train model 

train : True

### save model 

save : True

### save path : if null then the system will save the model in ./model_weights/model_class/network/weights/

save_path : ./model_weights/actor_critic/example/weights/

### testing model

test : True

### Visualize 

Visualize : False

### Submit

submit : False


####### Config specific to Actor Critic Agent ############

gamma : .99

nb_steps_warmup_critic  : 100

nb_steps_warmup_actor  : 100

target_model_update  : 1.0e-3

delta_clip :  1.


### Config Specific to the neural networks ####

#### memory  parameters

memoryLimit  : 100000
window_length  : 1

#### Random  process  parameters 
random_process_theta  : .15
random_process_mu  : 0.
random_process_sigma  : .2


